import { app, BrowserWindow, ipcMain, Menu, session } from "electron"; // Añadir 'session'
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    frame: false, // Desactiva el marco estándar
    titleBarStyle: "hidden", // Para macOS
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      webSecurity: true, // 🔐 ¡CAMBIO IMPORTANTE! Habilitar webSecurity
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Crear el menú personalizado (tu código de menú existente)
  const menuTemplate: Electron.MenuItemConstructorOptions[] = [
    {
      label: "Archivo",
      submenu: [
        {
          label: "Abrir",
          click: () => {
            console.log("Abrir archivo...");
          },
        },
        { label: "Salir", role: "quit" },
      ],
    },
    {
      label: "Editar",
      submenu: [
        { role: "undo", label: "Deshacer" },
        { role: "redo", label: "Rehacer" },
        { type: "separator" },
        { role: "cut", label: "Cortar" },
        { role: "copy", label: "Copiar" },
        { role: "paste", label: "Pegar" },
      ],
    },
    {
      label: "Ver",
      submenu: [
        { label: "Recargar", role: "reload" },
        { label: "Herramientas de desarrollo", role: "toggleDevTools" },
      ],
    },
  ];
  const menu = Menu.buildFromTemplate(menuTemplate);
  Menu.setApplicationMenu(menu);

  // Open the DevTools (descomenta si lo necesitas)
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
app.whenReady().then(() => {
  // Modificado para ser async si usas await dentro, o simplemente .then
  // Configurar CSP para todas las sesiones
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    const isDev = process.env.NODE_ENV === "development"; // O alguna otra forma de detectar el entorno

    const cspDirectives = [
      `default-src 'self'`,
      `script-src 'self' ${isDev ? "'unsafe-eval'" : ""}`, // 'unsafe-eval' para source maps de Webpack en dev
      // 👇 CAMBIO IMPORTANTE AQUÍ 👇
      `style-src 'self' 'unsafe-inline'`, // Permite 'self' Y estilos en línea (necesario para Emotion)
      `connect-src 'self' http://localhost:8080`,
      `connect-src 'self' http://localhost:9092`,
      `connect-src 'self' http://localhost:9000`,
      // Si Webpack Dev Server usa WebSockets para HMR y está en un puerto diferente:
      // `${isDev ? "ws://localhost:PUERTO_WEBPACK_DEV_SERVER" : ""}`, // Añadir a connect-src
      `img-src 'self' data:`,
      `font-src 'self' data:`,
      // ... otras directivas
    ];

    // Filtra directivas vacías y une
    const finalCsp = cspDirectives
      .map((d) => d.trim())
      .filter((d) => d && d.split(" ").length > 1) // Asegura que la directiva tenga al menos un valor además del tipo
      .join("; ");

    callback({
      responseHeaders: {
        ...details.responseHeaders,
        "Content-Security-Policy": [finalCsp],
      },
    });
  });

  createWindow();
});

// Tu código IPC y otros manejadores de eventos (sin cambios)
ipcMain.on("window:minimize", () => mainWindow?.minimize());
ipcMain.on("window:maximize", () => {
  if (mainWindow?.isMaximized()) {
    mainWindow.unmaximize();
  } else {
    mainWindow?.maximize();
  }
});
ipcMain.on("window:close", () => mainWindow?.close());

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
