import { app, BrowserWindow, ipcMain, session, shell } from "electron"; // Añadir 'session'
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    frame: false, // Desactiva el marco estándar
    titleBarStyle: "hidden", // Para macOS
    resizable: false,
    maximizable: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      webSecurity: true, // 🔐 ¡CAMBIO IMPORTANTE! Habilitar webSecurity
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

app.whenReady().then(() => {
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    const isDev = process.env.NODE_ENV === "development";

    const cspDirectives = [
      `default-src 'self'`,
      `script-src 'self' ${isDev ? "'unsafe-eval'" : ""}`,
      `style-src 'self' 'unsafe-inline'`,
      `connect-src 'self' http://localhost:8080`,
      `connect-src 'self' http://localhost:9092`,
      `connect-src 'self' http://localhost:9000`,
      `img-src 'self' data: http://localhost:9000`,
      `font-src 'self' data:`,
    ];

    // Filtra directivas vacías y une
    const finalCsp = cspDirectives
      .map((d) => d.trim())
      .filter((d) => d && d.split(" ").length > 1) // Asegura que la directiva tenga al menos un valor además del tipo
      .join("; ");

    callback({
      responseHeaders: {
        ...details.responseHeaders,
        "Content-Security-Policy": [finalCsp],
      },
    });
  });

  createWindow();
});

ipcMain.on("login-successful", () => {
  if (mainWindow) {
    mainWindow.setResizable(true);
    mainWindow.setMaximizable(true);

    mainWindow.setSize(1600, 900, true);
    mainWindow.center();
  }
});

ipcMain.on("logout-requested", () => {
  if (mainWindow) {
    mainWindow.unmaximize();
    mainWindow.setSize(800, 600, true);
    mainWindow.center();

    mainWindow.setMaximizable(false);
    mainWindow.setResizable(false);
  }
});

ipcMain.on("window:minimize", () => mainWindow?.minimize());
ipcMain.on("window:maximize", () => {
  if (mainWindow?.isMaximized()) {
    mainWindow.unmaximize();
  } else {
    mainWindow?.maximize();
  }
});
ipcMain.on("window:close", () => mainWindow?.close());

ipcMain.on("open-external", (_event, url: string) => {
  if (url && typeof url === "string") {
    shell.openExternal(url);
  }
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
